name: Build darksword-kexploit-fun Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: xcode-27

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Xcode 27
        run: |
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks

      - name: Show project information
        run: |
          xcodebuild \
            -list \
            -project "$PWD/darksword-kexploit-fun.xcodeproj"

      - name: Build unsigned archive
        run: |
          xcodebuild archive \
            -project "$PWD/darksword-kexploit-fun.xcodeproj" \
            -scheme "darksword-kexploit-fun" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$PWD/build/darksword-kexploit-fun.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create unsigned IPA
        run: |
          mkdir -p build/Payload

          cp -R \
            build/darksword-kexploit-fun.xcarchive/Products/Applications/*.app \
            build/Payload/

          cd build
          zip -r darksword-kexploit-fun-unsigned.ipa Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: darksword-kexploit-fun-unsigned-IPA
          path: build/darksword-kexploit-fun-unsigned.ipa